BXMSDOC-5900: Added lambda introspection section in performance tuning chapter
hmanwani-rh/kie-docs pull request #20
Opened 2020-05-28 08:54 UTC by hmanwani-rh

Added Use lambda introspection for executable models to configure the cache size section in performance tuning chapter
See JIRA: https://issues.redhat.com/browse/BXMSDOC-5900

Rendered Output:
[Decision engine in Red Hat Process Automation Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5900-RHPAM/#performance-tuning-decision-engine-ref_decision-engine)
[Decision engine in Red Hat Decision Manager](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5900-RHDM/#performance-tuning-decision-engine-ref_decision-engine)

2020-05-28 23:33 UTC, tkobayas requested changes

2020-05-28 23:33 UTC, tkobayas commented on doc-content/drools-docs/src/main/asciidoc/DecisionEngine/performance-tuning-decision-engine-ref.adoc
> +Use lambda introspection for executable models to configure the cache size::
LambdaIntrospector is used internally by default. This configuration is not to 'enable' it but to change the cache size. So the sentence would be like
```
Configure LambdaIntrospector cache size for executable model build::
```

2020-05-28 23:33 UTC, tkobayas commented on doc-content/drools-docs/src/main/asciidoc/DecisionEngine/performance-tuning-decision-engine-ref.adoc
> +You can enable lambda introspection to configure the size of `LambdaIntrospector.methodFingerprintsMap` cache. The default size of the cache for an executable model is `32`. Small cache size optimize
The explanation seems to encourage to set small cache size. But the default size '32' is fine for most cases. I think we should state it is a trade-off between memory and performance. So it would be like
```
You can configure the size of `LambdaIntrospector.methodFingerprintsMap` cache which is used in executable model build. The default size of the cache is `32`. Smaller cache size reduces the usage of memory while it may slow down the build performance. For example, you can configure system property `drools.lambda.introspector.cache.size` to `0` for the least memory usage.
```

2020-05-29 07:27 UTC, tkobayas approved these changes
LGTM. thanks!

2020-05-29 08:41 UTC, kaldesai approved these changes
Hey @hmanwani-rh , I reviewed the section and everything looks good to me.

2020-06-01 09:28 UTC, hellowdan approved these changes
it looks good to me, thanks!

2020-06-22 09:25 UTC, merged