WIP BXMSDOC-5309-master: Add new "Branches" section of endpoints for the Knowledge Store REST API
hmanwani-rh/kie-docs pull request #3
Opened 2020-02-05 10:07 UTC by hmanwani-rh

[RHPAM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5309-RHPAM/#knowledge-store-rest-api-branches-ref_kie-apis)
[RHDM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-5309-RHDM/#knowledge-store-rest-api-branches-ref_kie-apis)

Added Branches section of endpoints for knowledge store REST API in Kie-API doc

2020-02-05 16:45 UTC, caponetto requested changes

2020-02-05 16:45 UTC, caponetto commented on doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-branches-ref.adoc
> +[POST] /branches/{name}/maven/compile::
Referring to what has been stated below "_Compiles a specified branch in a specified project._",
the correct URL here should be `/spaces/{spaceName}/projects/{projectName}/branches/{name}/maven/compile`.
Another option is to make it clear in the introduction of this section (7.2.4.) that `/spaces/{spaceName}/projects/{projectName}` is part of the URL for all branch operations listed below. 

In any case, we have two additional parameters:
- spaceName: space name (required - string)
  /spaces/{`spaceName`}/projects/{projectName}/branches/{name}/maven/compile
- projectName: project name (required - string)
  /spaces/{spaceName}/projects/{`projectName`}/branches/{name}/maven/compile

Although `/spaces/{spaceName}/projects/{projectName}` has been discussed in the previous sections, in my opinion, it is important to make it clear to the user that the full URL is composed of: Base URL + Space part + Project part + Branch part.

For example:
`http://SERVER:PORT/{URL_COMPONENT_CENTRAL}/rest/spaces/{spaceName}/projects/{projectName}/branches/{name}/maven/compile`

2020-02-05 16:45 UTC, caponetto commented on doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-branches-ref.adoc
> +[POST] /branches/{name}/maven/install::
Same thing here (refer to my first comment).

2020-02-05 16:45 UTC, caponetto commented on doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-branches-ref.adoc
> +[POST] /branches/{name}/maven/test::
Same thing here (refer to my first comment).

2020-02-05 16:45 UTC, caponetto commented on doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-branches-ref.adoc
> +[POST] /branches/{name}/maven/deploy::
Same thing here (refer to my first comment).

2020-02-05 16:45 UTC, caponetto commented on doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-branches-ref.adoc
> +[GET] /branches::
Same thing here (refer to my first comment).

2020-02-05 16:45 UTC, caponetto commented on doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-branches-ref.adoc
> +[POST] /branches::
Same thing here (refer to my first comment).

2020-02-05 16:45 UTC, caponetto commented on doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-branches-ref.adoc
> +[DELETE] /branches/{name}::
Same thing here (refer to my first comment).

2020-02-05 16:45 UTC, caponetto commented on doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-branches-ref.adoc
> +|String
```suggestion
|Request body
```
Other tables are referring to types like this as `Request body`.

2020-02-06 15:00 UTC, sterobin reviewed
@hmanwani-rh , just one comment. Otherwise good. Excellent work on this Heena! You did an exceptional job following the pattern and voice of the doc. Doesn't look at all like a new writer took it over, which is the ideal. Thanks so much.

2020-02-06 15:00 UTC, sterobin commented on doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-branches-ref.adoc
> +Adds branch in a specified project and space.
Suggest "Adds a specified branch in ..." for consistency with the others and clarity.

2020-02-06 15:59 UTC, hmanwani-rh commented on doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-branches-ref.adoc
> +Adds branch in a specified project and space.
Thank you Stetson

2020-02-10 15:23 UTC, barboras7 commented
@hmanwani-rh,
looks good to me. One small suggestion - maybe it would be worth mentioning that if no branch is specified, the maven actions (test, compile, install & deploy) apply to the master branch 

For example:
`http://localhost:8080/business-central/rest/spaces/{spaceName}/projects/{projectName}/maven/install`

CC @caponetto, what do you think?

2020-02-10 16:06 UTC, caponetto commented
+1 for @barboras7 suggestion

2020-02-11 11:05 UTC, caponetto approved these changes

2020-02-11 11:11 UTC, hmanwani-rh commented on doc-content/shared-kie-docs/src/main/asciidoc/Workbench/RemoteAPI/knowledge-store-rest-api-branches-ref.adoc
> +[POST] /branches/{name}/maven/compile::
Thanks Guilherme for providing the inputs.

2020-02-11 12:03 UTC, merged