Adding PMML changes to Kogito microservices doc
hmanwani-rh/kie-docs pull request #61
Opened 2021-06-08 09:11 UTC by hmanwani-rh

See comment in JIRA: https://issues.redhat.com/browse/BXMSDOC-7403?focusedCommentId=16263324&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16263324

Doc preview:
[PART V. GETTING STARTED WITH KOGITO MICROSERVICES IN RED HAT PROCESS AUTOMATION MANAGER](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-kogito-pmml-RHPAM/#assembly-getting-started-kogit-microservices)

2021-06-10 13:02 UTC, jiripetrlik requested changes
@hmanwani-rh 
Hello here is my feedback and suggestions for these changes.

2021-06-10 13:02 UTC, jiripetrlik commented on doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
> +{KOGITO} microservices include example applications in the `{PRODUCT_FILE}-decision-services-quickstarts.zip` file. These example applications contain various types of services on Quarkus or Spring B
I would suggest to mention somewhere that it is necessary for user to add the following dependencies to pom of his Kogito application if he wants to use PMML in Kogito:
```
<dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-pmml</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jpmml</groupId>
      <artifactId>pmml-model</artifactId>
    </dependency>
```

@gitgabrio Can you please also confirm.

2021-06-10 13:02 UTC, jiripetrlik commented on doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
> +* `dmn-drools-quarkus-metrics` and `dmn-drools-springboot-metrics`: A decision service (on Quarkus or Spring Boot) that enables and consumes the runtime metrics monitoring feature in {KOGITO}.
Please mention somewhere that in order to use monitoring features it is necessary to add the following dependency into Kogito application:
For Quarkus
```
<dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>monitoring-prometheus-quarkus-addon</artifactId>
</dependency>
```
For Springboot:
```
<dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>monitoring-prometheus-springboot-addon</artifactId>
</dependency>
```
@r00ta
Please review and confirm.

2021-06-10 13:02 UTC, jiripetrlik commented on doc-content/enterprise-only/getting-started-kogito/con-rhpam-kogito-operator-with-prometheus-and-grafana.adoc
> +    app: onboarding-service
I would suggest to change the name of the example. Onboarding-service example utilizes also processes and processes are not planned to work in Kogito in RHDM/RHPAM 7.11. I would suggest to use "dmn-drools-springboot-metrics-service" instead. Please change values of "app" and "name" accordingly.

@r00ta
Can you please also review and confirm.

2021-06-10 13:02 UTC, jiripetrlik commented on doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
> +{KOGITO} microservices include example applications in the `{PRODUCT_FILE}-decision-services-quickstarts.zip` file. These example applications contain various types of services on Quarkus or Spring B
Can we provide a link to user with more detailed information about usage of PMML? Something like: "For more information about how to use PMML and DMN with PMML please see....

Here is the chapter about more detailed informations about PMML: https://issues.redhat.com/browse/BXMSDOC-7377

2021-06-10 13:36 UTC, gitgabrio commented on doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
> +{KOGITO} microservices include example applications in the `{PRODUCT_FILE}-decision-services-quickstarts.zip` file. These example applications contain various types of services on Quarkus or Spring B
@jiripetrlik You're right :+1:

2021-06-10 13:41 UTC, gitgabrio commented on doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
> +* `dmn-drools-quarkus-metrics` and `dmn-drools-springboot-metrics`: A decision service (on Quarkus or Spring Boot) that enables and consumes the runtime metrics monitoring feature in {KOGITO}.
Hi @hmanwani-rh. I do not see any reference to `pmml-only` examples.
@jiripetrlik @danielezonca: should them be included in this documentation ?

2021-06-11 11:28 UTC, danielezonca commented on doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
> +* `dmn-drools-quarkus-metrics` and `dmn-drools-springboot-metrics`: A decision service (on Quarkus or Spring Boot) that enables and consumes the runtime metrics monitoring feature in {KOGITO}.
I agree, we should mention the `pmml-quarkus-example`/`pmml-springboot-example` example too. They are part of [`productized` profile](https://github.com/kiegroup/kogito-examples/blob/1.5.x/pom.xml#L295-L296) so I expect are included in 7.11.

2021-06-11 11:41 UTC, r00ta reviewed
Should be add the list of supported algorithms in this documentation? If we don't specify it, the user might think that we support all the algorithms. If this info is already present somewhere else in the documentation, forget my comment :)

2021-06-11 11:41 UTC, r00ta commented on doc-content/enterprise-only/getting-started-kogito/con-rhpam-kogito-operator-with-prometheus-and-grafana.adoc
> +    app: onboarding-service
Yes, it would be better to use `dmn-drools-springboot-metrics-service` or `dmn-drools-quarkus-metrics-service`

2021-06-11 14:18 UTC, jiripetrlik commented on doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
> +* `dmn-drools-quarkus-metrics` and `dmn-drools-springboot-metrics`: A decision service (on Quarkus or Spring Boot) that enables and consumes the runtime metrics monitoring feature in {KOGITO}.
@gitgabrio @danielezonca
You are right. I'm sorry for forgetting those. Please add them as well.

2021-06-11 17:16 UTC, hmanwani-rh commented on doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
> +{KOGITO} microservices include example applications in the `{PRODUCT_FILE}-decision-services-quickstarts.zip` file. These example applications contain various types of services on Quarkus or Spring B
Done, added this dependency.

2021-06-11 17:16 UTC, hmanwani-rh commented on doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
> +* `dmn-drools-quarkus-metrics` and `dmn-drools-springboot-metrics`: A decision service (on Quarkus or Spring Boot) that enables and consumes the runtime metrics monitoring feature in {KOGITO}.
Done, added the dependency and pmml-only examples to the doc.

2021-06-11 17:16 UTC, hmanwani-rh commented on doc-content/enterprise-only/getting-started-kogito/con-rhpam-kogito-operator-with-prometheus-and-grafana.adoc
> +    app: onboarding-service
Done

2021-06-11 17:16 UTC, hmanwani-rh commented on doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
> +{KOGITO} microservices include example applications in the `{PRODUCT_FILE}-decision-services-quickstarts.zip` file. These example applications contain various types of services on Quarkus or Spring B
Done

2021-06-11 17:17 UTC, hmanwani-rh commented
> Should be add the list of supported algorithms in this documentation? If we don't specify it, the user might think that we support all the algorithms. If this info is already present somewhere else in the documentation, forget my comment :)

@r00ta the list of algorithms is already covered in the dedicated PMML doc for RHPAM. 
Thanks for raising this.

2021-06-11 17:18 UTC, hmanwani-rh commented
> @hmanwani-rh
> Hello here is my feedback and suggestions for these changes.

@jiripetrlik @gitgabrio @danielezonca @r00ta I've updated the doc as per provided suggestions. Can you please review one more time and share your feedback?

2021-06-14 09:12 UTC, gitgabrio commented
@hmanwani-rh 
Hi, I'm not sure this is correct
`pmml-quarkus-example and pmml-springboot-example: A decision service (on Quarkus or Spring Boot) that uses PMML to determine driver penalty and suspension based on traffic violations.`

I'm not even sure `decision service` is the correct term, actually it is a `prediction`: @danielezonca WDYT ?

2021-06-14 09:43 UTC, jiripetrlik approved these changes
@hmanwani-rh 
Looks good to me. Maybe please remove "to determine driver penalty and suspension based on traffic violations" part of sentence as @gitgabrio suggested. These examples usually contain multiple PMML examples and can be changed between versions. Information that project uses PMML is enough I think. Otherwise looks good to me. Approving.

2021-06-14 09:49 UTC, r00ta approved these changes

2021-06-14 09:55 UTC, danielezonca commented
> @hmanwani-rh
> Hi, I'm not sure this is correct
> `pmml-quarkus-example and pmml-springboot-example: A decision service (on Quarkus or Spring Boot) that uses PMML to determine driver penalty and suspension based on traffic violations.`
> 
> I'm not even sure `decision service` is the correct term, actually it is a `prediction`: @danielezonca WDYT ?

In this context "decision service" is used as generic term used to identify a service for decision automation, also DRL/rule services are mentioned as decision services so I think it is better to stay with "decision service".

2021-06-15 08:39 UTC, gitgabrio commented
Hi @hmanwani-rh 
Here
`pmml-quarkus-example and pmml-springboot-example: A decision service (on Quarkus or Spring Boot) that uses PMML to determine driver penalty and suspension based on traffic violations.`

-> ` to determine driver penalty and suspension based on traffic violations.` is to be removed.

2021-06-15 08:41 UTC, hmanwani-rh commented
> Hi @hmanwani-rh
> Here
> `pmml-quarkus-example and pmml-springboot-example: A decision service (on Quarkus or Spring Boot) that uses PMML to determine driver penalty and suspension based on traffic violations.`
> 
> -> ` to determine driver penalty and suspension based on traffic violations.` is to be removed.

@gitgabrio Done, Please check the latest commit. 
Thanks

2021-06-15 08:45 UTC, gitgabrio commented
@hmanwani-rh 
I still see that here http://file.pnq.redhat.com/~hmanwani/BXMSDOC-kogito-pmml-RHPAM/#assembly-getting-started-kogit-microservices. Is there another page I have to look at ?

2021-06-15 08:50 UTC, hmanwani-rh commented
> @hmanwani-rh
> I still see that here http://file.pnq.redhat.com/~hmanwani/BXMSDOC-kogito-pmml-RHPAM/#assembly-getting-started-kogit-microservices. Is there another page I have to look at ?

@gitgabrio Please refresh the link, now you'll see the update. Apologies, earlier I updated a different link.

2021-06-15 08:56 UTC, gitgabrio approved these changes
LGTM, thanks @hmanwani-rh

2021-06-15 09:10 UTC, briandooley requested changes

2021-06-15 09:10 UTC, briandooley commented on doc-content/enterprise-only/getting-started-kogito/con-rhpam-kogito-operator-with-prometheus-and-grafana.adoc
> +{KOGITO} in {PRODUCT} provides a `monitoring-prometheus-addon` add-on that enables Prometheus metrics monitoring for {KOGITO} microservices and generates Grafana dashboards that consume the default m
```suggestion
{KOGITO} in {PRODUCT} provides a `monitoring-prometheus-addon` add-on that enables Prometheus metrics monitoring for {KOGITO} microservices and generates Grafana dashboards that consume the default metrics exported by the add-on. The RHPAM {KOGITO} Operator uses the https://github.com/coreos/prometheus-operator[Prometheus Operator] to expose the metrics from your project for Prometheus to scrape. Due to this dependency, you must install the Prometheus Operator in the same namespace as your project.
```
Passive voice.

2021-06-15 09:10 UTC, briandooley commented on doc-content/enterprise-only/getting-started-kogito/con-rhpam-kogito-operator-with-prometheus-and-grafana.adoc
> +When you deploy a {KOGITO} microservice that uses the `monitoring-prometheus-addon` add-on and the Prometheus Operator is installed, the Red Hat Process Automation Manager {KOGITO} Operator creates a
```suggestion
When you deploy a {KOGITO} microservice that uses the `monitoring-prometheus-addon` add-on, and you have installed the Prometheus Operator, the Red Hat Process Automation Manager {KOGITO} Operator creates a `ServiceMonitor` custom resource to expose the metrics for Prometheus, as shown in the following example:
```
Passive voice.

2021-06-15 09:10 UTC, briandooley commented on doc-content/enterprise-only/getting-started-kogito/con-rhpam-kogito-operator-with-prometheus-and-grafana.adoc
> +After you configure your Prometheus resource with the `ServiceMonitor` resource, you can see the endpoint being scraped by Prometheus in the *Targets* page in the Prometheus web console. The metrics
```suggestion
After you configure your Prometheus resource with the `ServiceMonitor` resource, you can see the endpoint scraped by Prometheus in the *Targets* page in the Prometheus web console. The metrics exposed by the {PRODUCT} service appear in the *Graph* view.
```

"being" is redundant here.

2021-06-15 09:10 UTC, briandooley commented on doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
> +* `dmn-pmml-quarkus-example` and `dmn-pmml-springboot-example`: A decision service (on Quarkus or Spring Boot) that uses DMN and PMML to determine driver penalty and suspension based on traffic viola
ISG - "Avoid using parentheses in general text because text in parentheses is decreased in importance"
```suggestion
* `dmn-pmml-quarkus-example` and `dmn-pmml-springboot-example`: A decision service, on Quarkus or Spring Boot, that uses DMN and PMML to determine driver penalty and suspension based on traffic violations.
```

2021-06-15 09:10 UTC, briandooley commented on doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
> +* `dmn-drools-quarkus-metrics` and `dmn-drools-springboot-metrics`: A decision service (on Quarkus or Spring Boot) that enables and consumes the runtime metrics monitoring feature in {KOGITO}.
ISG - "Avoid using parentheses in general text because text in parentheses is decreased in importance"

2021-06-15 09:10 UTC, briandooley commented on doc-content/enterprise-only/getting-started-kogito/ref-kogito-microservices-app-examples.adoc
> +* `pmml-quarkus-example` and `pmml-springboot-example`: A decision service (on Quarkus or Spring Boot) that uses PMML.
ISG - "Avoid using parentheses in general text because text in parentheses is decreased in importance"

2021-06-15 12:15 UTC, merged